### ISSUE TITLE
Dump all watches and watch history as part of the diagnostic

### ISSUE THREAD

**Issue by geekpete** [elastic/support-diagnostics#187]
We only seem to grab the watcher_stats.json.
It might be nice to dump all the watches and watch history into the diag payload as well.

**Comment by nemonster** [comment]
Not as a default. Sorry to be that blunt, but there's no governor on the number and size of watches and how much history they keep. I'm getting 3 rollovers of logs now which is already expanding the size. So I am not inclined to go get everything but the kitchen sink just on the possibility that it *might* be relevant.

I'm open to making this a supplied type though - where you specify specifically "I want this potentially big thing and I know what I'm asking for," since I have another one of these requests open as well. So you'd have to say, "I want to look at your watches, run this specifically to get the output," as a discrete step.

**Comment by geekpete** [comment]
Good point and might be a nice as a separate option. 

Thanks

**Comment by nemonster** [comment]
OK, will look into it but it may be a few releases before you see anything...

**Comment by nemonster** [comment]
Closing this one for now given the changes to the direction of watches.
