### ISSUE TITLE
Improve messaging around Authentication failure

### ISSUE THREAD

**Issue by immon** [elastic/support-diagnostics#210]
Running the tool against a cluster with Security enabled but without `-u` and `-p` gives a message not clear enough. Users tend to think diagnostics bundle has been created correctly, but it includes nothing more than authentication error in diagnostics.log.

Message should be clear and recommend to use `-u` and `-p` if `401 Unauthorized` error is returned by ES.

Currently the tool ends with following message
```
17:13:47 INFO  Error retrieving Elasticsearch version  - unable to continue..  Please make sure the proper connection parameters were specified
```
The following message has been seen too, which is even more vague:
```
[support-diagnostics-6.4.1.jar:6.4.1]
Caused by: java.lang.IllegalArgumentException: major version [] is not supported by this diagnostics tool
```

**Comment by nemonster** [comment]
I don't have the actual log here, but I suspect this is not due to a missing id and password combination but rather a missing --ssl parameter. If the person running it didn't get the other two I suspect that was missing as well. In this instance an unauthenticated or unauthorized request should have still completed normally rather than throwing an exception. So it would have been due to the host being unreachable. 

On one hand, the instructions are pretty clear in that regard, and if you're not aware that you need to use TLS and credentials I don't think a more granular message is going to help much in this instance. Also, keep in mind that the full log with all the stack traces is inside the archive. That's the intent - most people running this are generally not going to be able to address most issues themselves historically. The full log is now in the archive so at least the support engineer can crack it open and see what they did.

However, it probably does help to provide a bit more of a hint, so I have reworked the messaging so that there is some additional information here that will given the SE some more background when and if they respond. So in the next version there will be a message indicating that there was an issue connecting to that host.
