### ISSUE TITLE
Output file corrupt after running diagnostic 6.3

### ISSUE THREAD

**Issue by svyahalkar** [elastic/support-diagnostics#214]
After running a diagnostic.sh, I get the bad file name and corrupt file in output. Even though I provide a password in the command line, it still asks for the password.

sudo ./diagnostics.sh -h <host_name> --port 9200 -u <user> --password <password>

-rw-r--r-- 1 root elasticsearch   10 Jul 26 17:25 -20180726-172516.tar.gz

**Comment by nemonster** [comment]
If you've got a tar.gz, I doubt if it's corrupt. Have you actually tried to extract the contents? The diagnostics.log will be in the archive and provide some additional insight. Just don't attach it here if there's anything sensitive in it.

But from looking at the command line you're showing, there's no username specified after the -u. The --password is entered without a value so you're prompted for a masked entry which won't be visible in the history but you do need to enter the username.  Try that.

**Comment by nemonster** [comment]
> Yes I am running the command with user and password

Not according to what you have on the command line. 

> sudo ./diagnostics.sh -h <host_name> --port 9200 -u --password

You're telling it that you are going to supply a username with the -u argument and then do not provide a value. Please see the readme for the proper syntax. 

As  for:

>  Another interesting thing is, it is creating network-cache-settings file. If you look at the size of tar.gz, it is very small and when I try to gunzip it, it throws an error.

I don't understand what the connection is here?  That file is normal output. The archive is small because:
1.  It can't retrieve much without the proper inputs. Even if it errors out it will create the archive so I have what it can get and a detailed log.
2. It's compressed. It's supposed to small.

But on OSX High Sierra, test files with the dash are unzipping fine as long as you preface the file with ./ or use a -- between the file and the command.  So I can't replicate that part of it. It's not particularly fruitful to pursue since it appears you're running it incorrectly. Try specifying the arguments with a username and if you still get a corrupt archive we can look further.

**Comment by svyahalkar** [comment]
Thanks Greg. It was nice talking to you. I am just providing here how we resolve this issue so other people can benefit.
Issue was I was providing password on command line only. i.e. after -p 

Also I was providing port number, but since we use default port 9200, there was no need to have that in command line. So after removing actual password and removing --port option, I was able to run command without any issues.

./diagnostics.sh -h <host_name> -u <elastic_user> -p

Thanks again Greg for all your help.
