### ISSUE TITLE
README Documentation questions

### ISSUE THREAD

**Issue by robin13** [elastic/support-diagnostics#226]
- [installation](https://github.com/elastic/support-diagnostics/blob/master/README.md#installation) - would it be appropriate to note here that the diagnostics utility does not need to be installed on a machine of the cluster (this is one of the biggest concerns of most users of the tool; manually installing a script in a production environment)
- [basic usage examples](https://github.com/elastic/support-diagnostics/blob/master/README.md#basic-usage-examples) - all of the examples are using sudo - is this really necessary?  Perhaps for the `localhost` example to be able to grab the logs, but even then, isn't sudo a bit much?  Similarly further down in the document in other examples.

**Comment by nemonster** [comment]
> installation - would it be appropriate to note here that the diagnostics utility does not need to be installed on a machine of the cluster (this is one of the biggest concerns of most users of the tool; manually installing a script in a production environment)

_**You mean like this?**_

_Remote
If you do not wish to run the utility on the host the node to be queried resides on, and wish to run it from a different host such as your workstation, you may use the --type remote option.
This will execute only the REST API calls and will not attempt to execute local system calls or collect log files.
Remote Example
 ./diagnostics.sh --host 10.0.0.20 --type remote_

>basic usage examples - all of the examples are using sudo - is this really necessary? Perhaps for the localhost example to be able to grab the logs, but even then, isn't sudo a bit much? Similarly further down in the document in other examples.

_In order to assure that all artifacts are collected it is recommended that you run the tool with elevated privileges. This means sudo on Linux type platforms and via an Administor Prompt in Windows_

Actually, depending on the privileges of the user running it a number of the command line system calls might fail. If you're running remote and/or don't care about that, feel free not to run sudo. 

If you read the entire passage above, it explains the rationale and you can make your own decision from there. Examples are for the basic cases that produce the most consistent results. If there are instances where someone has refused to run it because of that I can always consider reworking. But my question is how normal is it for someone who's maintaining a cluster and is running the utility in that kind of environment _not_ to have sudo access. I'd probably want to see some more specific concerns with some tangible examples before making too many changes along this line.

**Comment by robin13** [comment]
@nemonster 

> You mean like this?

Yes... I read the full documentation. :)  But I have also frequently experienced users of the tool who do not, and assume / try to install on prod with much strain, so it seems to me that it would be good to highlight the fact that it does not need to be installed on the Elasticsearch production cluster higher up in the docs at the point where installation is being discussed.

> But my question is how normal is it for someone who's maintaining a cluster and is running the utility in that kind of environment not to have sudo access?

I assume they usually _have_ sudo, but being asked to sudo some script without reviewing it first, and this is a whole java application... so review is difficult...  it's scary!  So I would rather give all the examples without sudo and if portions cannot be collected due to not having root, output a nice warning to the command line noting what could not be collected, and suggesting to run again with `sudo` to complete.

**Comment by nemonster** [comment]
I'm open to adding a note on the install. The sudo in the examples, no. Sorry, it addresses the most common case and there are commands that won't run with restricted access. It was put in there because there were so many instances where things didn't function properly. If you get general agreement among a majority of SE's that any command needing sudo can be removed from the set of executed defaults, I'm open to taking it out. But if not, it stays since the absence will cause errors and I get more issues on those than about having sudo in the examples.

**Comment by robin13** [comment]
Ok, +1 for adding a note on the install.  Would you rather do it yourself, or shall I do a PR?
