### ISSUE TITLE
[Feature Request] Make local mode's interactive prompts as configurable parameters

### ISSUE THREAD

**Issue by danielyahn** [elastic/support-diagnostics#252]
Hi, I love the new `--type local` feature. I'm in the process of orchestrating it on our cluster. However, I noticed that some of the parameters such as log directory is collected interactively. Is it possible to expose it as command line argument or `diags.yml`?

**Comment by nemonster** [comment]
That's interesting because I was getting ready to deprecate this or remove it outright in the next release. I have never seen anyone use it correctly. Ever. It seems to be an issue with reading the directions - people are surprised when they don't get REST call outputs, when the whole point of that was to collect system stats and logs without doing that. It causes issues with some internal analysis processes I have running that use the diags - going back to review the tickets those came from I have never seen a case where it was used as intended.

So I'm interested in how you're using it and how attached you are to it ATM. I have some ideas for an alternative way to handle the issue that you don't get those things collected running the standard diag on that single node. But again, I've never seen anyone actually use it as a collection shortcut.

I'm actually kind of loathe to keep it back in the standard diag given some of the changes. Let me ask you this - can you give me a more detailed run down of how you're using it. I may put it back as a standalone run with its own script like the scrub to keep it from impacting the collection of standard diagnostics.

**Comment by danielyahn** [comment]
I like the fact that (from README)
>  It will allow the logs to be collected for a non-running or hung node without having to manually go to the log directory. 

Currently, to upload logs on a dead node, I need to carefully select correct files and upload them. I was trying to do something like with my orchestration tooling:
```
On nodes ElasticSearch process is dead, 
1. In case of JVM OOME, Look for heap dump and upload.
2. Gather server logs and garbage collection logs and tarball them and upload. 
3. Run REST calls on live nodes and tarball them and upload. 
```

Well I ended up scripting out all the steps, but it would be something nice-to-have if all steps can be done with one command of the support-diagnostic tool.

On another note, I'm using a S3 bucket to share these data with support engineers. It would be really nice if the tool provides direct integration to S3 bucket. (and don't have to go through the support portal to upload everytime)

**Comment by nemonster** [comment]
@danielyahn The next version of the local option will be different than the current, and possibly more useful for you. There will be no cluster access or interactive responses, but you will need to specify the location of the log directory. See the revised instructions for the new calling mode.

Also note that this feature is under review, and might possibly be removed in the future.
