### ISSUE TITLE
Expose options to change the request and connect timeout

### ISSUE THREAD

**Issue by kostasb** [elastic/support-diagnostics#254]
The requestTimeout and connectTimeout settings are in the diags.yml

https://github.com/elastic/support-diagnostics/blob/master/src/main/resources/diags.yml

I believe this file was available in plain text with previous versions of the diagnostic tool and users were able to modify these values.

Currently (v6.4.4) the diag instructions are built into jar files and I don't see any option exposing the timeouts to make them configurable.

Impact: when calls with large outputs, i.e. a large cluster state, reach the timeout, there's no way to adjust it so that they can succeed.

**Comment by jakommo** [comment]
The docs also still mention this option [here](https://github.com/elastic/support-diagnostics#customizing-the-output)

**Comment by nemonster** [comment]
And as noted in the docs, it provides a package number. There are some build issues with keeping this in the root directory. And it has generally been unusual for anyone to have to modify this. If you do wish to do this, all you need to do is download the file and put it the diagnostic root directory as described,. 

My question would be on the actual timeout message. Do you have an issue number for the diagnostic where this error occurred?

**Comment by kostasb** [comment]
Case 00317882

diagnostic.log:

```
17:12:51.842 [main] INFO  com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd - Currently running query: _nodes/stats?pretty&human
17:13:21.891 [main] DIAG  com.elastic.support.util.RestExec - Query Execution Error
java.net.SocketTimeoutException: Read timed out
```

Is it possible to just drop a diags.yml file with whatever modified attributes they need, in the root directory of the diagnostic tool?

**Comment by nemonster** [comment]
I see you've deleted the case #, although it has no tie in since access to it is private and it doesn't identify any particular customer... Put it in support ops, or a direct message or email it to me, since that is not a stack trace and I'd like to see the whole thing to see what the timestamps in the logs and the full set of traces look like.

There are a couple of issues with what you're requesting. First off, that's a SocketTimeoutException, which means that it timed out on a read, not a connect. Neither of the timeout values that are in the file should have any impact on that. It happens on a socket that's already opened because it's been too long since any data packets came through it.

I don't set that value at all in this version. The next release of the diag will expose it though the reason to expose it is usually to reduce the timeout rather than extending it so you don't wait around forever on something that's compromised. Currently it will default to whatever the system is set to. IIRC the normal default for this on LInux is 2 hours. The network configuration and their host setting will have the biggest impact on whether this error occurs or not. One of these may be at fault, or in combination with a  firewall that's closing the connection if no data packets come through for a period of time.  Hard to say, but I don't think changing the request and connection timeout will generally help you.

But if you do want to experiment, any of the diag.yml settings can be changed. You just can't remove anything that it's going to need. IOW, if you're running on Windows and take out those commands, or if you're on 5.x and remove those you're going to have issues.

I didn't flesh it out too much because this _is_ an advanced option and historically hardly anyone ever edits it. Or needs to for that matter. If you have that need, all you have to do is extract it from the support-diagnostics-XXX.jar (from the zip distribution or alternatively from the source code archives or directly from Github via the RAW option. Take that, change your values and put it in the extracted support diagnostic's folder. That should get you there.

**Comment by kostasb** [comment]
@nemonster I'll ping you via a private channel to discuss the specifics for a case where increasing the request timeout helped the diags complete. You can then evaluate if we should be providing a flag to adjust it easily without having to place the a diags.yml in the root directory.
