### ISSUE TITLE
Should not prompt for latest version more than once

### ISSUE THREAD

**Issue by bilsch** [elastic/support-diagnostics#263]
```
Run 2 of 20 completed.
13:09:54 INFO  Next run will occur in 30 seconds.

13:10:24 INFO  Writing diagnostic manifest.
13:10:24 INFO  Configuring REST endpoint.
13:10:24 INFO  Trying REST Endpoint.
13:10:24 INFO  Checking for diagnostic version updates.
13:10:24 INFO  Warning: Diagnostic version:6.4.4 is not the current recommended release
13:10:24 INFO  The current release is 7.0.0
13:10:24 INFO  The latest version can be downloaded at
Continue anyway? [Y/N]
```

This prompt occurs between each iteration - should only prompt once for this.

**Comment by nemonster** [comment]
- It appears that you're using the multi-run functionality. That's been removed in 7.0.0. So it's not clear if you are running an old version because of that or just because you haven't updated? Knowing that might make it a little easier to answer.
- Going forward, if you need to do this, you'll need to just set up a script, cron job, or Windows task to fire off the diagnostic at your desired interval. 
- If you need to run the previous version because you want the multi-run capability, you wouldn't want to have functionality enabled that could generate a prompt anyway given that it was intended as kind of set and forget. It's assumed that if you're using more advanced functionality you probably are going to be aware of the version. So you would want to use --bypassDiagVerify when running a loop. That would be true for either the version you reference or the latest.

The multi-run functionality was originally added at the request of support engineers but was never extensively utilized. Given the state of the built in X-Pack monitoring it did not make sense to keep it in the application given that it creates some challenges moving forward with never functionality. 

So feel free to use it with the older version for now although at some point we may adjust the minimum diagnostic version upwards. The current minimum is 6.3.0.
