### ISSUE TITLE
Add `/_ssl/certificates` to API calls

### ISSUE THREAD

**Issue by robin13** [elastic/support-diagnostics#345]
Would it be possible to add `/_ssl/certificates` to the calls made?  Having this information would be helpful in many SSL related cases.

**Comment by pickypg** [comment]
FYI, the API only returns the certificates from the node you request it from.

This is an example of what it returns (from one of our dev cluster's):

```json
[
  {
    "path" : "internal_tls_ca.crt",
    "format" : "PEM",
    "alias" : null,
    "subject_dn" : "CN=elastic ce internal tls root",
    "serial_number" : "15ec82ab3ae",
    "has_private_key" : false,
    "expiry" : "2027-09-26T11:06:35.000Z"
  },
  {
    "path" : "node.crt",
    "format" : "PEM",
    "alias" : null,
    "subject_dn" : "CN=instance-0000000022.node.77aa4c2efaa04c9eac99ea9d91b26187.cluster.local",
    "serial_number" : "16ec95bf34d",
    "has_private_key" : true,
    "expiry" : "2029-11-30T01:24:36.000Z"
  }
]
```

**Comment by pickypg** [comment]
@nemonster is going to take a look at this.

**Comment by pickypg** [comment]
We've discussed this after stewing on it for a week, and while we think the data would be valuable, it wouldn't be valuable in the way that Elasticsearch provides it (a particular node).

With that in mind, we think that perhaps this should become an enhancement request for the ES team to make the call federated across the nodes (e.g., `/_nodes/ssl/certificates`) rather than just the node you talk to so that it actually provides value to the diagnostic. Otherwise the value in having it is highly limited since, generally speaking, _we_ don't know which node was used and it doesn't even tell you (e.g., in a SaaS environment, the proxy may shift this call to a different node).

**Comment by robin13** [comment]
Fair point - I've created the issue here: https://github.com/elastic/elasticsearch/issues/50432
