### ISSUE TITLE
Elaborate on "Could not retrieve the Elasticsearch version due to a system or network error - unable to continue."

### ISSUE THREAD

**Issue by toby-sutor** [elastic/support-diagnostics#389]
We see a lot of users running the script behind a proxy or firewall and I personally think it is unnecessary to hard fail the script because of the failed version check.

That being said, could we please elaborate on this error and add a reference to use 
`--bypassDiagVerify`?

E.g. turn 
> Could not retrieve the Elasticsearch version due to a system or network error - unable to continue.

into:

> Could not retrieve the Elasticsearch version due to a system or network error - unable to continue. If you still want to continue without checking for the latest version, please use the --bypassDiagVerify option.

**Comment by nemonster** [comment]
I'll put in some additional verbiage for this error. But unfortunately you've misconstrued what it is telling you. That message has absolutely nothing to do with a firewall cutting the diagnostic off from GH. Run a test yourself and try it. If the diagnostic cannot reach GH then it will simply output a message stating that and prompt the user to continue so they at least see it. After that it will continue as normal. So you are mistaken in that it fails the diagnostic if it can't get the diagnostic version. That --bypassDiagVerify only turns off the message and prompt to continue.

This message: 

> Could not retrieve the Elasticsearch version due to a system or network error - unable to continue.

is generated during the first operation of the diagnostic where it determines what calls to run by first checking what version of Elasticsearch is the target. If this fails it is usually due to incorrect information supplied in the parameter list. Such as an invalid host.  I actually do provide a overview of what the sequence of events are in the section titled: *Overview*.

>When the utility runs it will first check to see if there is a more current version and display an alert message if it is out of date. From there it will connect to the host input in the command line parameters, authenticate if necessary, check the Elasticsearch version, and get a listing of available nodes and their configurations. From there it will run a series of REST API calls specific to the version that was found. If the node configuration info shows a master with an HTTP listener configured all the REST calls will be run against that master. Otherwise the node on the host that was input will be used.
>

So it actually _is_ explained, but I'll put a specific line in the troubleshooting section so that it's fairly stark in terms of meaning. 

But if someone has issues connecting I would suggest looking in the archive that's produced for the diagnostic log. That will still happen when all but the most egregious of errors occur. And will often provide a clue as to what is causing it to fail. Depending on what you'd see there I would suggest a more specific ticket if this is due to an issue with the functionality.

**Comment by toby-sutor** [comment]
You are correct. I misread the error messages in two instances where the version check error was right above the actual message of the diag not being able to get the ES version:

```
Failed to get current diagnostic version from Github.
If Github is not accessible from this environemnt current supported version cannot be confirmed.
Getting Elasticsearch Version.
Could not retrieve the Elasticsearch version - unable to continue.
```

Thank you for the clarification and apologies for the positive.
