### ISSUE TITLE
ipv6 addresses incorrectly scrubbed

### ISSUE THREAD

**Issue by immon** [elastic/support-diagnostics#391]
[0,1,2,1]
1. ipv6 addresses, unlike ipv4, are replaced to the constant value `XXXX.XXXX.XXXX.XXXX.XXXX.XXXX.XXXX.XXXX` instead of new random IP address used consistently across diagnostic files. Ref: https://github.com/elastic/support-diagnostics/blob/8.0.3/src/main/java/com/elastic/support/scrub/ScrubProcessor.java#L196
2. ipv6 regexp pattern is incorrect and lines like `      "transport_address" : "[2a00:babe:babe::303]:9300",` are replaced to `      "transport_address" : "[XXXX.XXXX.XXXX.XXXX.XXXX.XXXX.XXXX.XXXX303]:9300",` where the last address part is retained.

**Comment by nemonster** [comment]
The question is why you need these to be handled in the same way as the ipv4 addresses? The reason I process the ipv4 address that way is because failing to do so creates issues with the analyzer. But I don't really use that transport address field for anything other than display. 

I don't have any objections to processing these in the same fashion, but scheduling it requires a priority and that hinges on the contextual difficulties it creates.

**Comment by immon** [comment]
For consistency with ipv4 behavior, for matching the functionality advertised in README (` The utility will automatically obfuscate all IPv4, IPv6 and MAC addresses`).

Not sure what issues with the analyzer you saw, but I'd expect to see the same ones for clusters using ipv6 addresses only (when ipv6 regexp pattern gets fixed)

Feel free to close the issue or let's clarify in README that v6 addresses and MAC addresses are not fully obfuscated.

**Comment by nemonster** [comment]
If you have a set of analyzed output where this causes the nodes_hot_threads to fail, can you make arrangements to provide it? It does obfuscate them. Just not the same way as the IPv4. Again, I do intend to make some changes to the obfuscation routines and will address this at that time. But keep in mind that these are prioritized based how it impacts the overall end result, so there is a need to demonstrate the degree to which it impacts the workflow.
