### ISSUE TITLE
Capture output of _cat snapshots 

### ISSUE THREAD

**Issue by robin13** [elastic/support-diagnostics#415]
It is sometimes necessary to know if recent snapshots were successful or not.  Would it be possible to add the `/_cat/snapshots` call to the diagnostics queries?

**Comment by jpcarey** [comment]
Does this endpoint just query some sort of cached state, or does it need to go read all the metadata files stored within each repo / snapshot? If the later, I'd be worried about collecting this by default. One of the old cluster's that I managed would take ~2 minutes to list snapshots due to the number of snapshots & s3...

**Comment by nemonster** [comment]
As outlined above this is potentially an expensive call to be running by default. And in fact, there are a LOT of calls made by the diag that I think would be better served as a second pass rather than as an initial collection. 

But at this point I'm exposing all the configuration in the /config directory of the diag so there's a middle ground I'm going to tread here.

So I'm going to add this, but commented out by default. If it's something that you think you want, please instruct whoever is running it to uncomment it out in the elasticsearch-rest.yml file before executing. If there aren't any horror stories after a while we can see about making it run by default.
