### ISSUE TITLE
Add an option to disable potentially memory-expensive calls when creating the diagnostic, and don't retry them

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/support-diagnostics#420]
Some REST calls can be very expensive in a cluster that is oversharded. Just to put an example: 
- Recently, I did run the diagnostic tool in a cluster with 20K shards, for which the indices could have up to thousands of fields. 
- The call to `GET _segments` did effectively put too much memory pressure in the receiving node and it ended up dying with an OOM error. 
  - Elasticsearch team is already considering adding a circuit breaker to prevent these - https://github.com/elastic/elasticsearch/issues/42318 
- If I got the diagnostic tool right, it will retry this call several times by default if it fails before effectively stopping. 
  - In this case, the diagnostic had been taken against a load balancer (not directly a node), so this caused the high memory pressure issue in several nodes in sequence as they started to fail. 

I am fully aware the cluster had a bad design from the shards point of view, but it is usual to find those.

**Comment by nemonster** [comment]
Usually cluster state is the main offender in terms of memory. It's kind of hard to predict this kind of failure with any certainty. What I _am_ going to do is expose the configuration files in a config directory. So if you saw this kind of behavior you could easily remove either the call and/or the retry.

**Comment by nemonster** [comment]
@ismael-hasan You actually can already override the retry behavior via the elasticsearch-rest.yml file. Thing was, you had to extract it from the archive and copy it into the utility directory. Now all the config files are exposed in the /config directory in the installation directory of the diagnostic.

To remove a particular call, just comment it out. Only calls with the 
``` retry: true ``` 
parameter will be retried. You can delete it, comment it out, or simply change it to false. If it's not there, it won't be retried since the default value is false.
