### ISSUE TITLE
-i doesn't work as input argument

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/support-diagnostics#421]
```
$ ./import-monitoring.sh --host localhost -i /Users/jay/diags/00496771/monitoring-export-20200520-104157.tar.gz --clusterName netsuite --indexName netsuite_monitoring
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Processing diagnosticInputs...
Error occurred: Was passed main parameter '-i' but no main parameter was defined in your arg class. Check diagnostics.log in the archive file for more detail.
~/workspace/support-diagnostics-8.0.3
$ ./import-monitoring.sh --host localhost --input /Users/jay/diags/00496771/monitoring-export-20200520-104157.tar.gz --clusterName netsuite --indexName netsuite_monitoring
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Processing diagnosticInputs...
Deleted directory: /Users/jay/workspace/support-diagnostics-8.0.3/monitoring-export.
Creating temp directory: /Users/jay/workspace/support-diagnostics-8.0.3/monitoring-export
Configuring log file.
Extracting archive...
Processing: index_stats.json
Indexing document batch 0 to 250
Indexing document batch 250 to 500
Indexing document batch 500 to 750
Indexing document batch 750 to 1000
Indexing document batch 1000 to 1250
```

Also there's a related error in the docs - `-clusterName` vs `--clusterName`

**Comment by nemonster** [comment]
@PhaedrusTheGreek 
I was a little confused by this as first, since there's no -i parameter in the parameter table. But then I looked at the examples and saw it, as well as the one with the single dash in clusterName. It was copied from the text of the scrub evidently and forgot to change all the parameters. The evils of of copy/paste once again...

Actually, there's another one in the table, where the parameter clusterName is correct but the example usage is clustername in all lower case. 

I'll take another pass through these since there are some other things to put out this week and get it fixed ASAP.

**Comment by nemonster** [comment]
@PhaedrusTheGreek As I've been reworking scrub and adding to the monitoring extract I've brought these input parameters into alignment, hopefully.  Everything will be standardized on -i and --input, similar to -o and --output. So at least it's consistent.
