### ISSUE TITLE
indices_stats.json fails if indices are closed

### ISSUE THREAD

**Issue by robin13** [elastic/support-diagnostics#438]
If an index is closed, when `indices_stats.json` is created, it results in the file containing:

```
Bad Request. Rejected
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_closed_exception",
        "reason" : "closed",
        "index_uuid" : "Hauu9raRRg-UAGBtWAPzCw",
        "index" : "my-closed-index"
      }

    ],
    "type" : "index_closed_exception",
    "reason" : "closed",
    "index_uuid" : "Hauu9raRRg-UAGBtWAPzCw",
    "index" : "my-closed-index"
  },
  "status" : 400
}
```

This is a real bother because a closed index can cause all useful data to be missing here...
Could it be that `forbid_closed_indices` is set to false (default is true)?

**Comment by nemonster** [comment]
This issue has exactly _zero_  to do with the diagnostic utility. 

First off, no diagnostic version provided, no Elasticsearch version, no logging, not console output. Not much to go on.

* Checking this against a 7.5.2 cluster did not exhibit the behavior.
* Ran against a 7.7.0 and an error occurred as soon as an index was closed. Even a plain vanilla _stats with no options fails. And no, forbid_closed indices was *not* set to false, and even it was, it had no impact. BTW, you can see the exact text of the call if you look in elastic-rest.yml in the config directory. And it's in GH as well so it's not hard to find.
* Then ran against 7.8.0 to see if it was still there. And voila, it goes away.
* Moved back to 7.7.1, and it's also fixed there.

So this appears to have been an issue in the 7.7.0 release that was fixed in subsequent releases. I can't do anything about the one that is broken within the diagnostic. And even if it was still broken, I wouldn't be able to. The diagnostic only runs calls that are already there. If one doesn't work that's easily verified outside of the scope of the diag. So for future reference the  appropriate repo to report it would have. been _elasticsearch_.
