### ISSUE TITLE
Checksum for diagnostics

### ISSUE THREAD

**Issue by robin13** [elastic/support-diagnostics#69]
Possible to create a checksum for all files included, just to be sure that nothing has become corrupted (or manually changed) in transit.

**Comment by jjfalling** [comment]
++

**Comment by nemonster** [comment]
The archive or all the individual files contained?  And do you have any stats on the numbers of archives that are, in fact, corrupted?  Where in transit are you worried about it being changed?

**Comment by robin13** [comment]
Best would be a checksum file listing all files created by the diagnostics tool with the checksum of each file, that way it will be possible to identify if individual files are changed/removed.  The checksum file must be included _in_ the resulting archive.

I have heard of cases where nodes have been removed from node stats to make it seem as if a cluster has less nodes than it does, or other data changed making review / support misleading.

**Comment by nemonster** [comment]
At this point if someone just went in and changed node_stats, and/or nodes there would be a number of areas in the analyzer that would fail. The subsequent errors would probably be sufficient to flag not only the anomaly but also point to what the discrepancies were. So unless there are some specific cases where we're trying to address this I'm not sure this offers any significant ROI. And even then, per this case I'd say you would just want to do nodes.json rather than all files in the payload.

**Comment by nemonster** [comment]
Retiring this one for now unless it is flagged as a more common concern. It will remain for future reference.
